import AboutUs from "./_components/about-section";
import Accreditation from "./_components/accreditations-section";
import Achievements from "./_components/achievements-section";
import BrandPartner from "./_components/brand-partner-section";
import HeroSection from "./_components/hero-section";
import NewsEvent from "./_components/news-events-section";
import Services from "./_components/services-section";

export const metadata = {
  title: "Adamallys | Home",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <main>
      <HeroSection />
      <Accreditation />
      <AboutUs />
      <Services />
      <Achievements />
      <BrandPartner />
      <NewsEvent />
    </main>
  );
}
